/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type ChatType = 'direct' | 'group';

export type FolderSpecialUse = 'archive' | 'drafts' | 'inbox' | 'junk' | 'sent' | 'trash';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JobStatus = 'done' | 'failed' | 'pending' | 'processing';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MailActionType =
  'create_folder' | 'delete' | 'delete_folder' | 'move' | 'rename_folder' | 'restore' | 'set_flag';

export type MailboxRole = 'editor' | 'mailbox_admin' | 'viewer';

export type MailboxStatus = 'active' | 'disabled' | 'error' | 'pending';

export type MemberStatus = 'active' | 'disabled';

export type MessageDirection = 'inbound' | 'outbound';

export type NotificationType =
  'action_failed' | 'assignment' | 'chat_message' | 'mailbox_error' | 'mention' | 'send_failed';

export type OutboxKind = 'forward' | 'new' | 'reply' | 'reply_all';

export type OutboxStatus =
  'canceled' | 'draft' | 'failed' | 'queued' | 'scheduled' | 'sending' | 'sent';

export type QueueStatus =
  'awaiting_reply' | 'done' | 'in_progress' | 'none' | 'scheduled' | 'to_reply';

export type RuleScope = 'mailbox' | 'personal';

export type TenantRole = 'admin' | 'member' | 'owner' | 'supervisor';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Attachments {
  content_id: string | null;
  content_type: Generated<string>;
  created_at: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  is_inline: Generated<boolean>;
  mailbox_id: string;
  message_id: string;
  size_bytes: Generated<number>;
  storage_path: string;
  tenant_id: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  id: Generated<Int8>;
  ip: string | null;
  metadata: Generated<Json>;
  tenant_id: string;
}

export interface ChatConversations {
  created_at: Generated<Timestamp>;
  created_by: string;
  direct_key: string | null;
  id: Generated<string>;
  last_message_at: Timestamp | null;
  name: string | null;
  tenant_id: string;
  type: ChatType;
  updated_at: Generated<Timestamp>;
}

export interface ChatMessages {
  body: Generated<string>;
  client_id: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  id: Generated<string>;
  sender_id: string;
  shared_snapshot: Json | null;
  shared_thread_id: string | null;
  tenant_id: string;
}

export interface ChatParticipants {
  conversation_id: string;
  joined_at: Generated<Timestamp>;
  last_read_at: Timestamp | null;
  left_at: Timestamp | null;
  tenant_id: string;
  user_id: string;
}

export interface ContactUserNicknames {
  tenant_id: string;
  contact_id: string;
  user_id: string;
  nickname: string;
}

export interface ContactEmails {
  agenda_user_id: string | null;
  is_primary: Generated<boolean>;
  contact_id: string;
  email: string;
  id: Generated<string>;
  label: Generated<string>;
  tenant_id: string;
}

export interface Contacts {
  scope: Generated<'tenant' | 'personal'>;
  owner_user_id: string | null;
  updated_by: string | null;
  version: Generated<number>;
  company: Generated<string>;
  first_name: Generated<string>;
  middle_name: Generated<string>;
  last_name: Generated<string>;
  prefix: Generated<string>;
  suffix: Generated<string>;
  department: Generated<string>;
  office: Generated<string>;
  website: Generated<string>;
  birthday: Generated<string>;
  addresses: Generated<JsonValue>;
  job_title: Generated<string>;
  phones: Generated<JsonValue>;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  name: string;
  notes: Generated<string>;
  phone: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface FolderPermissions {
  folder_id: string;
  mailbox_id: string;
  tenant_id: string;
  user_id: string;
}

export interface Folders {
  is_local: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  delimiter: Generated<string>;
  id: Generated<string>;
  imap_path: string;
  initial_uid_end: Int8 | null;
  last_uid: Generated<Int8>;
  mailbox_id: string;
  name: string;
  parent_id: string | null;
  sort_order: Generated<number>;
  special_use: FolderSpecialUse | null;
  special_use_official: Generated<boolean>;
  tenant_id: string;
  uidvalidity: Int8 | null;
  updated_at: Generated<Timestamp>;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  capabilities: Generated<string[]>;
  created_at: Generated<Timestamp>;
  delivery_error: string | null;
  delivery_status: Generated<string>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string;
  mailbox_roles: Generated<Json>;
  revoked_at: Timestamp | null;
  sender_context: Generated<string>;
  sender_mailbox_id: string | null;
  tenant_id: string;
  tenant_role: Generated<TenantRole>;
  token_hash: string;
}

export interface MailActions {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  mailbox_id: string;
  payload: Json;
  processed_at: Timestamp | null;
  requested_by: string | null;
  status: Generated<JobStatus>;
  tenant_id: string;
  type: MailActionType;
}

export interface MailboxCredentials {
  encrypted_password: string;
  mailbox_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Mailboxes {
  receiving_protocol: Generated<'imap' | 'pop3' | 'local'>;
  aliases: Generated<string[]>;
  append_sent_copy: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  email_address: string;
  from_name_template: Generated<string>;
  history_classify_days: Generated<number>;
  id: Generated<string>;
  imap_host: string;
  imap_port: Generated<number>;
  imap_secure: Generated<boolean>;
  import_started_at: Timestamp | null;
  last_error: string | null;
  last_reconciled_at: Timestamp | null;
  last_synced_at: Timestamp | null;
  name: string;
  smtp_host: string;
  smtp_port: Generated<number>;
  smtp_secure: Generated<boolean>;
  status: Generated<MailboxStatus>;
  sync_since: Generated<Timestamp>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface MailboxMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mailbox_id: string;
  restrict_to_folders: Generated<boolean>;
  role: MailboxRole;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MailRules {
  review_reason: string | null;
  actions: Json;
  conditions: Json;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mailbox_id: string;
  match_mode: Generated<string>;
  name: string;
  owner_user_id: string | null;
  priority: Generated<number>;
  scope: RuleScope;
  stop_processing: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  source_kind: Generated<'imap' | 'pop3' | 'archive'>;
  source_key: string | null;
  raw_storage_path: string | null;
  bcc_addresses: Generated<Json>;
  body_html: string | null;
  body_text: Generated<string>;
  cc_addresses: Generated<Json>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  direction: MessageDirection;
  folder_id: string | null;
  from_address: Generated<string>;
  from_name: Generated<string>;
  has_attachments: Generated<boolean>;
  id: Generated<string>;
  imap_uid: Int8 | null;
  in_reply_to: string | null;
  is_automated: Generated<boolean>;
  is_flagged: Generated<boolean>;
  is_historical: Generated<boolean>;
  mailbox_id: string;
  message_at: Timestamp;
  message_id_header: string;
  outbox_id: string | null;
  pending_action: Generated<boolean>;
  references_headers: Generated<string[]>;
  reply_to_addresses: Generated<Json>;
  rules_applied_at: Timestamp | null;
  rules_inbox: Generated<boolean>;
  search_vector: string | null;
  sent_by_user_id: string | null;
  size_bytes: Generated<number>;
  snippet: Generated<string>;
  subject: Generated<string>;
  tenant_id: string;
  thread_id: string;
  to_addresses: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  body: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  link: string | null;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  tenant_id: string;
  title: string;
  type: NotificationType;
  user_id: string;
}

export interface OperationalLogs {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  level: string;
  message: string;
  metadata: Generated<Json>;
  request_id: string | null;
  service: string;
  tenant_id: string | null;
}

export interface Outbox {
  attachments: Generated<Json>;
  attempts: Generated<number>;
  bcc_addresses: Generated<Json>;
  body_html: Generated<string>;
  cc_addresses: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string;
  created_by_rule_id: string | null;
  id: Generated<string>;
  job_id: string | null;
  kind: Generated<OutboxKind>;
  last_error: string | null;
  mailbox_id: string;
  message_id_header: string | null;
  reply_to_message_id: string | null;
  scheduled_at: Timestamp | null;
  send_after: Timestamp | null;
  sent_at: Timestamp | null;
  sent_message_id: string | null;
  signature_id: string | null;
  status: Generated<OutboxStatus>;
  subject: Generated<string>;
  submit_count: Generated<number>;
  tenant_id: string;
  thread_id: string | null;
  to_addresses: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface PersonalLabels {
  mailbox_mode: Generated<'all' | 'selected'>;
  scope: Generated<'personal' | 'tenant'>;
  created_by: string | null;
  color: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface PlatformAdmins {
  created_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlatformAudit {
  action: string;
  actor_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  request_id: string | null;
  tenant_id: string | null;
}

export interface PlatformMetricSamples {
  id: Generated<Int8>;
  measured_at: Generated<Timestamp>;
  metrics: Json;
  source: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  version: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface SignatureImages {
  content_type: string;
  created_at: Generated<Timestamp>;
  height: number;
  id: Generated<string>;
  legacy_public: Generated<boolean>;
  size_bytes: number;
  storage_path: string;
  tenant_id: string;
  user_id: string;
  width: number;
}

export interface Signatures {
  body_html: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  mailbox_id: string | null;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface StorageAssetRefs {
  asset_id: string;
  created_at: Generated<Timestamp>;
  mailbox_id: string | null;
  source_id: string;
  source_kind: string;
  tenant_id: string | null;
}

export interface StorageAssets {
  allocated_bytes: Int8 | null;
  category: Generated<string>;
  created_at: Generated<Timestamp>;
  expected_bytes: Int8 | null;
  id: Generated<string>;
  last_scan_id: string | null;
  mailbox_id: string | null;
  observed_at: Timestamp | null;
  physical_key: string | null;
  present_bytes: Int8 | null;
  revision: Generated<Int8>;
  scope: Generated<string>;
  state: Generated<string>;
  storage_key: string;
  tenant_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface StorageDiscrepancies {
  asset_id: string | null;
  code: string;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  mailbox_id: string | null;
  resolved_at: Timestamp | null;
  tenant_id: string | null;
}

export interface StorageLogicalCatalog {
  category: string;
  excluded_columns: string[];
  owner_column: string;
  relation_name: string;
}

export interface StorageLogicalPayloads {
  body_bytes: Int8;
  category: string;
  mailbox_id: string | null;
  metadata_bytes: Int8;
  relation_name: string;
  retained: boolean;
  row_key: string;
  tenant_id: string | null;
}

export interface StorageLogicalRowsV3 {
  body_bytes: Int8 | null;
  category: string | null;
  mailbox_id: string | null;
  metadata_bytes: Int8 | null;
  retained: boolean | null;
  tenant_id: string | null;
}

export interface StorageOperations {
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  operation: string;
  state: Generated<string>;
  storage_key: string;
}

export interface StorageScanRuns {
  checked_files: Generated<Int8>;
  created_at: Generated<Timestamp>;
  cursor: string | null;
  error_code: string | null;
  error_count: Generated<Int8>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  mode: string;
  published_at: Timestamp | null;
  requested_by: string | null;
  started_at: Timestamp | null;
  state: Generated<string>;
  tenant_id: string | null;
}

export interface StorageUsageSnapshots {
  categories: Json;
  formula_version: string;
  id: Generated<Int8>;
  mailbox_id: string | null;
  measured_at: Generated<Timestamp>;
  quality: string;
  scan_id: string | null;
  scope: string;
  scope_id: string;
  tenant_id: string | null;
  usage: Json;
}

export interface SupportSessions {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  expires_at: Timestamp;
  id: Generated<string>;
  reason: string;
  session_hash: string;
  tenant_id: string;
  user_id: string;
}

export interface TablePreferences {
  config: Json;
  list_key: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantMembers {
  capabilities: Generated<string[]>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: Generated<TenantRole>;
  status: Generated<MemberStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  suspended_at: Timestamp | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ThreadNotes {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  mailbox_id: string;
  mentioned_user_ids: Generated<string[]>;
  tenant_id: string;
  thread_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ThreadPersonalLabels {
  applied_by: string | null;
  created_at: Generated<Timestamp>;
  label_id: string;
  tenant_id: string;
  thread_id: string;
  user_id: string | null;
}

export interface Threads {
  assigned_at: Timestamp | null;
  assigned_to: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  first_inbound_at: Timestamp | null;
  first_message_at: Timestamp | null;
  first_response_at: Timestamp | null;
  has_attachments: Generated<boolean>;
  history_queue_eligible: Generated<boolean>;
  id: Generated<string>;
  last_inbound_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_outbound_at: Timestamp | null;
  mailbox_id: string;
  manual_done_at: Timestamp | null;
  message_count: Generated<number>;
  participants: Generated<string[]>;
  queue_excluded: Generated<boolean>;
  queue_status: Generated<QueueStatus>;
  queue_status_changed_at: Generated<Timestamp>;
  snippet: Generated<string>;
  subject: Generated<string>;
  subject_normalized: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ThreadStatusHistory {
  changed_by: string | null;
  created_at: Generated<Timestamp>;
  from_status: QueueStatus | null;
  id: Generated<string>;
  mailbox_id: string;
  reason: string;
  tenant_id: string;
  thread_id: string;
  to_status: QueueStatus;
}

export interface ThreadUserState {
  is_pinned: Generated<boolean>;
  last_read_at: Timestamp | null;
  tenant_id: string;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Uploads {
  mailbox_id: string | null;
  consumed_at: Timestamp | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  size_bytes: number;
  storage_path: string;
  tenant_id: string;
  user_id: string;
}

export interface UserPreferences {
  density: Generated<string>;
  desktop_notifications: Generated<boolean>;
  load_remote_images: Generated<boolean>;
  notify_assignments: Generated<boolean>;
  notify_chat: Generated<boolean>;
  notify_mentions: Generated<boolean>;
  theme: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  avatar_path: string | null;
  created_at: Generated<Timestamp>;
  current_tenant_id: string | null;
  email: string;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  mail_archive_imports: {
    id: Generated<string>;
    tenant_id: string;
    mailbox_id: string;
    created_by: string;
    filename: string;
    format: string;
    size_bytes: Int8;
    storage_path: string | null;
    state: Generated<string>;
    cursor: Generated<number>;
    imported: Generated<number>;
    skipped: Generated<number>;
    last_error: string | null;
    created_at: Generated<Timestamp>;
    updated_at: Generated<Timestamp>;
  };
  label_mailboxes: { tenant_id: string; label_id: string; mailbox_id: string };
  contact_imports: {
    duplicates: string | null;
    id: Generated<string>;
    tenant_id: string;
    user_id: string;
    mode: string;
    rows: JsonValue;
    results: Generated<JsonValue>;
    cursor: Generated<number>;
    created_at: Generated<Timestamp>;
    expires_at: Generated<Timestamp>;
  };
  attachments: Attachments;
  audit_logs: AuditLogs;
  chat_conversations: ChatConversations;
  chat_messages: ChatMessages;
  chat_participants: ChatParticipants;
  contact_user_nicknames: ContactUserNicknames;
  contact_emails: ContactEmails;
  contacts: Contacts;
  folder_permissions: FolderPermissions;
  folders: Folders;
  invitations: Invitations;
  mail_actions: MailActions;
  mail_rules: MailRules;
  mailbox_credentials: MailboxCredentials;
  mailbox_members: MailboxMembers;
  mailboxes: Mailboxes;
  messages: Messages;
  notifications: Notifications;
  operational_logs: OperationalLogs;
  outbox: Outbox;
  password_reset_tokens: PasswordResetTokens;
  personal_labels: PersonalLabels;
  platform_admins: PlatformAdmins;
  platform_audit: PlatformAudit;
  platform_metric_samples: PlatformMetricSamples;
  schema_migrations: SchemaMigrations;
  sessions: Sessions;
  signature_images: SignatureImages;
  signatures: Signatures;
  storage_asset_refs: StorageAssetRefs;
  storage_assets: StorageAssets;
  storage_discrepancies: StorageDiscrepancies;
  storage_logical_catalog: StorageLogicalCatalog;
  storage_logical_payloads: StorageLogicalPayloads;
  storage_logical_rows_v3: StorageLogicalRowsV3;
  storage_operations: StorageOperations;
  storage_scan_runs: StorageScanRuns;
  storage_usage_snapshots: StorageUsageSnapshots;
  support_sessions: SupportSessions;
  table_preferences: TablePreferences;
  tenant_members: TenantMembers;
  tenants: Tenants;
  thread_notes: ThreadNotes;
  thread_personal_labels: ThreadPersonalLabels;
  thread_status_history: ThreadStatusHistory;
  thread_user_state: ThreadUserState;
  threads: Threads;
  uploads: Uploads;
  user_preferences: UserPreferences;
  users: Users;
}
