/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FolderSpecialUse = "archive" | "drafts" | "inbox" | "junk" | "sent" | "trash";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type JobStatus = "done" | "failed" | "pending" | "processing";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MailActionType = "create_folder" | "delete" | "delete_folder" | "move" | "rename_folder" | "restore" | "set_flag";

export type MailboxRole = "editor" | "mailbox_admin" | "viewer";

export type MailboxStatus = "active" | "disabled" | "error" | "pending";

export type MemberStatus = "active" | "disabled";

export type MessageDirection = "inbound" | "outbound";

export type NotificationType = "action_failed" | "assignment" | "chat_message" | "mailbox_error" | "mention" | "send_failed";

export type OutboxKind = "forward" | "new" | "reply" | "reply_all";

export type OutboxStatus = "canceled" | "draft" | "failed" | "queued" | "scheduled" | "sending" | "sent";

export type QueueStatus = "awaiting_reply" | "done" | "in_progress" | "none" | "scheduled" | "to_reply";

export type RuleScope = "mailbox" | "personal";

export type TenantRole = "admin" | "member" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Attachments {
  content_id: string | null;
  content_type: Generated<string>;
  created_at: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  is_inline: Generated<boolean>;
  mailbox_id: string;
  message_id: string;
  size_bytes: Generated<number>;
  storage_path: string;
  tenant_id: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  id: Generated<Int8>;
  ip: string | null;
  metadata: Generated<Json>;
  tenant_id: string;
}

export interface Folders {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  delimiter: Generated<string>;
  id: Generated<string>;
  imap_path: string;
  last_uid: Generated<Int8>;
  mailbox_id: string;
  name: string;
  parent_id: string | null;
  sort_order: Generated<number>;
  special_use: FolderSpecialUse | null;
  tenant_id: string;
  uidvalidity: Int8 | null;
  updated_at: Generated<Timestamp>;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string;
  mailbox_roles: Generated<Json>;
  revoked_at: Timestamp | null;
  tenant_id: string;
  tenant_role: Generated<TenantRole>;
  token_hash: string;
}

export interface MailActions {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  mailbox_id: string;
  payload: Json;
  processed_at: Timestamp | null;
  requested_by: string | null;
  status: Generated<JobStatus>;
  tenant_id: string;
  type: MailActionType;
}

export interface MailboxCredentials {
  encrypted_password: string;
  mailbox_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Mailboxes {
  aliases: Generated<string[]>;
  append_sent_copy: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  email_address: string;
  from_name_template: Generated<string>;
  id: Generated<string>;
  imap_host: string;
  imap_port: Generated<number>;
  imap_secure: Generated<boolean>;
  last_error: string | null;
  last_reconciled_at: Timestamp | null;
  last_synced_at: Timestamp | null;
  name: string;
  smtp_host: string;
  smtp_port: Generated<number>;
  smtp_secure: Generated<boolean>;
  status: Generated<MailboxStatus>;
  sync_since: Generated<Timestamp>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface MailboxMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mailbox_id: string;
  role: MailboxRole;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MailRules {
  actions: Json;
  conditions: Json;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  mailbox_id: string;
  match_mode: Generated<string>;
  name: string;
  owner_user_id: string | null;
  priority: Generated<number>;
  scope: RuleScope;
  stop_processing: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Messages {
  bcc_addresses: Generated<Json>;
  body_html: string | null;
  body_text: Generated<string>;
  cc_addresses: Generated<Json>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  direction: MessageDirection;
  folder_id: string | null;
  from_address: Generated<string>;
  from_name: Generated<string>;
  has_attachments: Generated<boolean>;
  id: Generated<string>;
  imap_uid: Int8 | null;
  in_reply_to: string | null;
  is_automated: Generated<boolean>;
  is_flagged: Generated<boolean>;
  mailbox_id: string;
  message_at: Timestamp;
  message_id_header: string;
  outbox_id: string | null;
  pending_action: Generated<boolean>;
  references_headers: Generated<string[]>;
  reply_to_addresses: Generated<Json>;
  rules_applied_at: Timestamp | null;
  rules_inbox: Generated<boolean>;
  search_vector: string | null;
  sent_by_user_id: string | null;
  size_bytes: Generated<number>;
  snippet: Generated<string>;
  subject: Generated<string>;
  tenant_id: string;
  thread_id: string;
  to_addresses: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  body: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  link: string | null;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  tenant_id: string;
  title: string;
  type: NotificationType;
  user_id: string;
}

export interface Outbox {
  attachments: Generated<Json>;
  attempts: Generated<number>;
  bcc_addresses: Generated<Json>;
  body_html: Generated<string>;
  cc_addresses: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string;
  created_by_rule_id: string | null;
  id: Generated<string>;
  job_id: string | null;
  kind: Generated<OutboxKind>;
  last_error: string | null;
  mailbox_id: string;
  message_id_header: string | null;
  reply_to_message_id: string | null;
  scheduled_at: Timestamp | null;
  send_after: Timestamp | null;
  sent_at: Timestamp | null;
  sent_message_id: string | null;
  signature_id: string | null;
  status: Generated<OutboxStatus>;
  subject: Generated<string>;
  submit_count: Generated<number>;
  tenant_id: string;
  thread_id: string | null;
  to_addresses: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface PersonalLabels {
  color: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  version: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Signatures {
  body_html: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  mailbox_id: string | null;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TablePreferences {
  config: Json;
  list_key: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: Generated<TenantRole>;
  status: Generated<MemberStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ThreadNotes {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  mailbox_id: string;
  mentioned_user_ids: Generated<string[]>;
  tenant_id: string;
  thread_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ThreadPersonalLabels {
  created_at: Generated<Timestamp>;
  label_id: string;
  tenant_id: string;
  thread_id: string;
  user_id: string;
}

export interface Threads {
  assigned_at: Timestamp | null;
  assigned_to: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  first_inbound_at: Timestamp | null;
  first_message_at: Timestamp | null;
  first_response_at: Timestamp | null;
  has_attachments: Generated<boolean>;
  id: Generated<string>;
  last_inbound_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_outbound_at: Timestamp | null;
  mailbox_id: string;
  manual_done_at: Timestamp | null;
  message_count: Generated<number>;
  participants: Generated<string[]>;
  queue_excluded: Generated<boolean>;
  queue_status: Generated<QueueStatus>;
  queue_status_changed_at: Generated<Timestamp>;
  snippet: Generated<string>;
  subject: Generated<string>;
  subject_normalized: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ThreadStatusHistory {
  changed_by: string | null;
  created_at: Generated<Timestamp>;
  from_status: QueueStatus | null;
  id: Generated<string>;
  mailbox_id: string;
  reason: string;
  tenant_id: string;
  thread_id: string;
  to_status: QueueStatus;
}

export interface ThreadUserState {
  is_pinned: Generated<boolean>;
  last_read_at: Timestamp | null;
  tenant_id: string;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Uploads {
  consumed_at: Timestamp | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  size_bytes: number;
  storage_path: string;
  tenant_id: string;
  user_id: string;
}

export interface UserPreferences {
  density: Generated<string>;
  desktop_notifications: Generated<boolean>;
  load_remote_images: Generated<boolean>;
  notify_assignments: Generated<boolean>;
  notify_chat: Generated<boolean>;
  notify_mentions: Generated<boolean>;
  theme: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  avatar_path: string | null;
  created_at: Generated<Timestamp>;
  current_tenant_id: string | null;
  email: string;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  attachments: Attachments;
  audit_logs: AuditLogs;
  folders: Folders;
  invitations: Invitations;
  mail_actions: MailActions;
  mail_rules: MailRules;
  mailbox_credentials: MailboxCredentials;
  mailbox_members: MailboxMembers;
  mailboxes: Mailboxes;
  messages: Messages;
  notifications: Notifications;
  outbox: Outbox;
  password_reset_tokens: PasswordResetTokens;
  personal_labels: PersonalLabels;
  schema_migrations: SchemaMigrations;
  sessions: Sessions;
  signatures: Signatures;
  table_preferences: TablePreferences;
  tenant_members: TenantMembers;
  tenants: Tenants;
  thread_notes: ThreadNotes;
  thread_personal_labels: ThreadPersonalLabels;
  thread_status_history: ThreadStatusHistory;
  thread_user_state: ThreadUserState;
  threads: Threads;
  uploads: Uploads;
  user_preferences: UserPreferences;
  users: Users;
}
