/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppScheduledRouteImport } from './routes/_app.scheduled'
import { Route as DevUiRouteImport } from './routes/[_]dev.ui'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppChatConversationIdRouteImport } from './routes/_app.chat.$conversationId'
import { Route as AppMailMailboxIdRouteImport } from './routes/_app.mail.$mailboxId'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppSettingsLabelsRouteImport } from './routes/_app.settings.labels'
import { Route as AppSettingsMailboxesRouteImport } from './routes/_app.settings.mailboxes'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsRulesRouteImport } from './routes/_app.settings.rules'
import { Route as AppSettingsSignaturesRouteImport } from './routes/_app.settings.signatures'
import { Route as AppSettingsTenantRouteImport } from './routes/_app.settings.tenant'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsMailboxesMailboxIdRouteImport } from './routes/_app.settings.mailboxes_.$mailboxId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduledRoute = AppScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AppRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/_dev/ui',
  path: '/_dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppMailMailboxIdRoute = AppMailMailboxIdRouteImport.update({
  id: '/mail/$mailboxId',
  path: '/mail/$mailboxId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLabelsRoute = AppSettingsLabelsRouteImport.update({
  id: '/settings/labels',
  path: '/settings/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMailboxesRoute = AppSettingsMailboxesRouteImport.update({
  id: '/settings/mailboxes',
  path: '/settings/mailboxes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRulesRoute = AppSettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSignaturesRoute = AppSettingsSignaturesRouteImport.update({
  id: '/settings/signatures',
  path: '/settings/signatures',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTenantRoute = AppSettingsTenantRouteImport.update({
  id: '/settings/tenant',
  path: '/settings/tenant',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMailboxesMailboxIdRoute =
  AppSettingsMailboxesMailboxIdRouteImport.update({
    id: '/settings/mailboxes_/$mailboxId',
    path: '/settings/mailboxes/$mailboxId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/chat': typeof AppChatRouteWithChildren
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/scheduled': typeof AppScheduledRoute
  '/_dev/ui': typeof DevUiRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/mail/$mailboxId': typeof AppMailMailboxIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/labels': typeof AppSettingsLabelsRoute
  '/settings/mailboxes': typeof AppSettingsMailboxesRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/settings/signatures': typeof AppSettingsSignaturesRoute
  '/settings/tenant': typeof AppSettingsTenantRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/chat/': typeof AppChatIndexRoute
  '/settings/mailboxes/$mailboxId': typeof AppSettingsMailboxesMailboxIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/scheduled': typeof AppScheduledRoute
  '/_dev/ui': typeof DevUiRoute
  '/': typeof AppIndexRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/mail/$mailboxId': typeof AppMailMailboxIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/labels': typeof AppSettingsLabelsRoute
  '/settings/mailboxes': typeof AppSettingsMailboxesRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/settings/signatures': typeof AppSettingsSignaturesRoute
  '/settings/tenant': typeof AppSettingsTenantRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/chat': typeof AppChatIndexRoute
  '/settings/mailboxes/$mailboxId': typeof AppSettingsMailboxesMailboxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/scheduled': typeof AppScheduledRoute
  '/_dev/ui': typeof DevUiRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/_app/mail/$mailboxId': typeof AppMailMailboxIdRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/labels': typeof AppSettingsLabelsRoute
  '/_app/settings/mailboxes': typeof AppSettingsMailboxesRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/rules': typeof AppSettingsRulesRoute
  '/_app/settings/signatures': typeof AppSettingsSignaturesRoute
  '/_app/settings/tenant': typeof AppSettingsTenantRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/settings/mailboxes_/$mailboxId': typeof AppSettingsMailboxesMailboxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/superadmin'
    | '/chat'
    | '/contacts'
    | '/dashboard'
    | '/scheduled'
    | '/_dev/ui'
    | '/chat/$conversationId'
    | '/mail/$mailboxId'
    | '/settings/audit'
    | '/settings/labels'
    | '/settings/mailboxes'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/rules'
    | '/settings/signatures'
    | '/settings/tenant'
    | '/settings/users'
    | '/chat/'
    | '/settings/mailboxes/$mailboxId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/superadmin'
    | '/contacts'
    | '/dashboard'
    | '/scheduled'
    | '/_dev/ui'
    | '/'
    | '/chat/$conversationId'
    | '/mail/$mailboxId'
    | '/settings/audit'
    | '/settings/labels'
    | '/settings/mailboxes'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/rules'
    | '/settings/signatures'
    | '/settings/tenant'
    | '/settings/users'
    | '/chat'
    | '/settings/mailboxes/$mailboxId'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/superadmin'
    | '/_app/chat'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/scheduled'
    | '/_dev/ui'
    | '/_app/'
    | '/_app/chat/$conversationId'
    | '/_app/mail/$mailboxId'
    | '/_app/settings/audit'
    | '/_app/settings/labels'
    | '/_app/settings/mailboxes'
    | '/_app/settings/preferences'
    | '/_app/settings/profile'
    | '/_app/settings/rules'
    | '/_app/settings/signatures'
    | '/_app/settings/tenant'
    | '/_app/settings/users'
    | '/_app/chat/'
    | '/_app/settings/mailboxes_/$mailboxId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduled': {
      id: '/_app/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AppScheduledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_dev/ui': {
      id: '/_dev/ui'
      path: '/_dev/ui'
      fullPath: '/_dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$conversationId': {
      id: '/_app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/mail/$mailboxId': {
      id: '/_app/mail/$mailboxId'
      path: '/mail/$mailboxId'
      fullPath: '/mail/$mailboxId'
      preLoaderRoute: typeof AppMailMailboxIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/labels': {
      id: '/_app/settings/labels'
      path: '/settings/labels'
      fullPath: '/settings/labels'
      preLoaderRoute: typeof AppSettingsLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/mailboxes': {
      id: '/_app/settings/mailboxes'
      path: '/settings/mailboxes'
      fullPath: '/settings/mailboxes'
      preLoaderRoute: typeof AppSettingsMailboxesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/rules': {
      id: '/_app/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AppSettingsRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/signatures': {
      id: '/_app/settings/signatures'
      path: '/settings/signatures'
      fullPath: '/settings/signatures'
      preLoaderRoute: typeof AppSettingsSignaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tenant': {
      id: '/_app/settings/tenant'
      path: '/settings/tenant'
      fullPath: '/settings/tenant'
      preLoaderRoute: typeof AppSettingsTenantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/mailboxes_/$mailboxId': {
      id: '/_app/settings/mailboxes_/$mailboxId'
      path: '/settings/mailboxes/$mailboxId'
      fullPath: '/settings/mailboxes/$mailboxId'
      preLoaderRoute: typeof AppSettingsMailboxesMailboxIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppScheduledRoute: typeof AppScheduledRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMailMailboxIdRoute: typeof AppMailMailboxIdRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsLabelsRoute: typeof AppSettingsLabelsRoute
  AppSettingsMailboxesRoute: typeof AppSettingsMailboxesRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsRulesRoute: typeof AppSettingsRulesRoute
  AppSettingsSignaturesRoute: typeof AppSettingsSignaturesRoute
  AppSettingsTenantRoute: typeof AppSettingsTenantRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsMailboxesMailboxIdRoute: typeof AppSettingsMailboxesMailboxIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppScheduledRoute: AppScheduledRoute,
  AppIndexRoute: AppIndexRoute,
  AppMailMailboxIdRoute: AppMailMailboxIdRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsLabelsRoute: AppSettingsLabelsRoute,
  AppSettingsMailboxesRoute: AppSettingsMailboxesRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsRulesRoute: AppSettingsRulesRoute,
  AppSettingsSignaturesRoute: AppSettingsSignaturesRoute,
  AppSettingsTenantRoute: AppSettingsTenantRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsMailboxesMailboxIdRoute: AppSettingsMailboxesMailboxIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
