export const AUDIT_ACTION_LABELS: Record<string, string> = {
  'contact.created': 'Contato criado',
  'contact.updated': 'Contato atualizado',
  'contact.deleted': 'Contato excluído',
  'platform.support_started': 'Suporte iniciado',
  'platform.support_ended': 'Suporte encerrado',
  'platform.support_read': 'Consulta em suporte',
  'platform.tenant_created': 'Empresa criada pela plataforma',
  'platform.tenant_suspended': 'Empresa suspensa',
  'platform.tenant_resumed': 'Empresa reativada',
  'platform.mailbox_created': 'Caixa criada pela plataforma',
  'platform.mailbox_credentials_replaced': 'Credencial substituída pela plataforma',
  'auth.login': 'Entrada na conta',
  'auth.login_failed': 'Tentativa de entrada recusada',
  'auth.password_changed': 'Senha alterada',
  'tenant.updated': 'Empresa atualizada',
  'member.invited': 'Convite enviado',
  'member.invite_revoked': 'Convite revogado',
  'member.joined': 'Convite aceito',
  'member.access_updated': 'Permissões atualizadas',
  'member.status_changed': 'Status do usuário alterado',
  'mailbox.created': 'Caixa criada',
  'mailbox.updated': 'Caixa atualizada',
  'mailbox.credentials_updated': 'Credenciais da caixa atualizadas',
  'mailbox.disabled': 'Caixa desativada',
  'mailbox.enabled': 'Caixa ativada',
  'mailbox.connection_error': 'Falha de conexão da caixa',
  'mailbox_member.updated': 'Acesso à caixa atualizado',
  'folder.created': 'Pasta criada',
  'folder.renamed': 'Pasta renomeada',
  'folder.deleted': 'Pasta excluída',
  'rule.created': 'Regra criada',
  'rule.updated': 'Regra atualizada',
  'rule.deleted': 'Regra excluída',
  'message.sent': 'E-mail enviado',
  'message.moved': 'Mensagem movida',
  'message.deleted': 'Mensagem excluída',
  'message.restored': 'Mensagem restaurada',
  'outbox.canceled': 'Envio cancelado',
  'thread.status_changed': 'Status da conversa alterado',
  'thread.assigned': 'Responsável atribuído',
  'thread.done': 'Conversa concluída',
  'thread.reopen': 'Conversa reaberta',
  'thread.excluded': 'Participação nas filas alterada',
};
